import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: '%s | LIAVI',
    default: 'LIAVI', // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-col bg-primary text-gray-900'>
      <Navbar></Navbar>
      <main className='flex-1'>
        {children}
      </main>
      <footer className='bg-white shadow-inner px-6 py-4 text-center text-sm text-gray-500'>
        © 2025 Liavi. Fet amb 💙 per estudiants.
      </footer>
    </div>
      </body>
    </html>
  );
}
